export const imageDetails = [
  {
    image: "/assets/image1.png",
    url: "/",
    id: "1",
    description: "Nude Maxi Bodycon dress",
    name: "Imani",
  },
  {
    image: "/assets/image.png",
    url: "/",
    id: "2",
    description: "Short chiffon black dress",
    name: "Evadore",
  },
  {
    image: "/assets/image7.png",
    url: "/",
    id: "7",
    description: "Midi Length crepe dress",
    name: "Olessia",
  },
  {
    image: "/assets/image5.png",
    url: "/",
    id: "5",
    description: "2 piece Sweatshirt & Skirt",
    name: "Olive",
  },
  {
    image: "/assets/image5.png",
    url: "/",
    id: "5",
    description: "2 piece Sweatshirt & Skirt",
    name: "Olive",
  },
  {
    image: "/assets/image.png",
    url: "/",
    id: "2",
    description: "Short chiffon black dress",
    name: "Evadore",
  },
  {
    image: "/assets/image1.png",
    url: "/",
    id: "1",
    description: "Nude Maxi Bodycon dress",
    name: "Imani",
  },
  {
    image: "/assets/image7.png",
    url: "/",
    id: "7",
    description: "Midi Length crepe dress",
    name: "Olessia",
  },
  {
    image: "/assets/image.png",
    url: "/",
    id: "2",
    description: "Short chiffon black dress",
    name: "Evadore",
  },
  {
    image: "/assets/image7.png",
    url: "/",
    id: "7",
    description: "Midi Length crepe dress",
    name: "Olessia",
  },
  {
    image: "/assets/image5.png",
    url: "/",
    id: "5",
    description: "2 piece Sweatshirt & Skirt",
    name: "Olive",
  },
  {
    image: "/assets/image1.png",
    url: "/",
    id: "1",
    description: "Nude Maxi Bodycon dress",
    name: "Imani",
  },
  {
    image: "/assets/image1.png",
    url: "/",
    id: "1",
    description: "Nude Maxi Bodycon dress",
    name: "Imani",
  },
  {
    image: "/assets/image5.png",
    url: "/",
    id: "5",
    description: "2 piece Sweatshirt & Skirt",
    name: "Olive",
  },
  {
    image: "/assets/image.png",
    url: "/",
    id: "2",
    description: "Short chiffon black dress",
    name: "Evadore",
  },
  {
    image: "/assets/image7.png",
    url: "/",
    id: "7",
    description: "Midi Length crepe dress",
    name: "Olessia",
  },
];

export const navLinks = [
  { title: "WHAT'S NEW", url: "/new" },
  { title: "SALES", url: "/new" },
  { title: "SHOP", url: "/" },
  { title: "COLLECTIONS", url: "/new" },
  { title: "STORES", url: "/new" },
  { title: "BLOG", url: "/new" },
];
